sudo: false
language: ruby
before_install: gem install bundler -v 2.0.1
matrix:
  include:
    - gemfile: graphql-1.7.gemfile
      env: GRAPHQL_RUBY_VERSION=1_7 CI=true
      rvm: 2.3.8
    - gemfile: graphql-1.8.gemfile
      env: GRAPHQL_RUBY_VERSION=1_8 CI=true
      rvm: 2.3.8
    - gemfile: graphql-1.7.gemfile
      env: GRAPHQL_RUBY_VERSION=1_7 CI=true
      rvm: 2.4.5
    - gemfile: graphql-1.8.gemfile
      env: GRAPHQL_RUBY_VERSION=1_8 CI=true
      rvm: 2.4.5
    - gemfile: graphql-1.7.gemfile
      env: GRAPHQL_RUBY_VERSION=1_7 CI=true
      rvm: 2.5.3
    - gemfile: graphql-1.8.gemfile
      env: GRAPHQL_RUBY_VERSION=1_8 CI=true
      rvm: 2.5.3
